version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: rds_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: rds_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "6500:5432"
    networks:
      - internal

  rds_backend_server:
    build: .
    container_name: rds_backend_server
    environment:
      DB_USER: admin
      DB_PASSWORD: P@ssw0rd
      DB_NAME: rds_db
      DB_HOST: postgres  # Use service name here
      DB_PORT: 5432      # PostgreSQL default port
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - internal
    command: air ./cmd/server/main.go

networks:
    internal:
      driver: bridge

volumes:
  postgres-data:

